### ISSUE TITLE
Error serializing package 'hidpi

### ISSUE THREAD

**Issue by cloud-walker** [mcanders/atom-hidpi#19]
I got this error periodically in dev mode

<img width="1079" alt="screen shot 2017-03-16 at 17 05 47" src="https://cloud.githubusercontent.com/assets/1144075/24006023/d6814eba-0a6a-11e7-9f0e-14bd1ad47f30.png">

**Comment by ghost** [comment]
+1 Any chance for a fix? It seems to make linter throw weird errors. Thanks for the fantastic package!
