### ISSUE TITLE
Menu bar 

### ISSUE THREAD

**Issue by benfeatherstone** [mcanders/atom-hidpi#7]
Is there any way to fix the menu bar so that the font matches the rest of the scaling and doesn't get cut off at the bottom? It might also need padding.

Ubuntu 14.04
Gnome 3.16
Atom 1.0.11
Screen resolution 3200 x 1800

![screenshot from 2015-09-02 22-09-16](https://cloud.githubusercontent.com/assets/7890249/9649806/a453f61e-51bf-11e5-970c-99a86a5246f4.png)

**Comment by cart** [comment]
I'm pretty sure the menubar is controlled by the chrome part of electrolysis.  I think the only way you can edit it is by changing your gtk theme.  But i'll look onto it.

**Comment by cart** [comment]
I'm closing this because there is nothing I can do about it
