### ISSUE TITLE
Broken with 1.2.1

### ISSUE THREAD

**Issue by raphael** [mcanders/atom-hidpi#8]
Since I've upgraded to Atom 1.2.1 the package doesn't seem to change the scale factor anymore (stays too big). I'm on Linux if that makes a difference, happy to provide more information if needed.

**Comment by ricardomatias** [comment]
+1 on Arch Linux with Retina screen

**Comment by cart** [comment]
That's unfortunate.  I'll check it out later today.  I'm running arch with a retina screen so hopefully I can replicate this.

**Comment by cart** [comment]
I haven't looked at it that much yet, but it appears to be a resolution reporting issue.  I was able to enable scaling by setting a low cutoff width and height.  However the scale factor now scales half as much as it used to (2x scaling is now 1x).  I also noticed that atom correctly scaled 2x (my gnome-shell scale factor) without atom-hidpi enabled.  I guess I no longer need this addon as I only use one screen.  However I guess people with multiple displays with different dpis will still have a use for it.  I'll try to find a solution that takes into account the scale factor and adjusts accordingly.

**Comment by raphael** [comment]
Thanks for looking into it! I fall into the "people with multiple displays with different dpis" category :) Specifically my laptop is hidpi while my external display (which is where I would like to run Atom) isn't. I have been able to work around it for now by running `atom --high-dpi-support=1 --force-device-scale-factor=1`, the obvious drawback being that it won't auto-magically change dpi when dragging from one monitor to the other.

**Comment by FossPrime** [comment]
@raphael you can force the dpi by setting the cutoff width to something really low and then the scale factor to 0.5. That will effectively disable hidpi mode. Manual resolution scale factors seem to not work at all.

UPDATE
`atom --high-dpi-support=1 --force-device-scale-factor=1`
Was a perfect temporary fix. HiDPI will automagically resize as expected when you do that, I just had to put all the settings back to default and set "Update On Resize"

**Comment by COLABORATI** [comment]
Is it possible to add these settings to the atom configuration? If yes, how should this exactly look like in the config file? I tried several variations without success, so I am asking here just to be sure how the conifg syntax for these settings actually look like. Thanks for your attention!

**Comment by cart** [comment]
This should be fixed now by setting the atom-hidpi "Operating System Scale Factor" configuration option to your OS scale factor (likely 2.0 for the people in this thread).  Unfortunately, I couldn't find a way to automatically detect the scale factor, so this will be an "opt in" fix.

Can someone confirm that this works for them?

**Comment by raphael** [comment]
This fixes it, thank you! (and yes OS scale factor is 2 in my case).

**Comment by Reyncor** [comment]
Wish we had a way to debug what numbers atom-hidpi was seeing. I can't seems to make it respond to monitor changes. Yes update on resize is on.

I'm on Fedora 23 with Gnome Shell 3.18.3, every other feature seems to work, that is to say when I change the HiDPI setting to 1, it shrinks everything.
